default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rewardBoy_api_development
  username: root
  password: 2009060944
  host: localhost

test:
  <<: *default
  database: rewardBoy_api_test
  username: root
  password: 2009060944
  host: localhost

production:
  <<: *default
  database: reward_boy
  url: postgresql://root:2mFwCEnl4lBiz7Z802tOlXVu0XPt5Co1@dpg-crdgq9t2ng1s73fuusd0-a/reward_boy
  username: root
  password: 2mFwCEnl4lBiz7Z802tOlXVu0XPt5Co1
  host: dpg-crdgq9t2ng1s73fuusd0-a
  port: 5432
