default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rewardBoy_api_development
  username: root
  password: 2009060944
  host: localhost

test:
  <<: *default
  database: rewardBoy_api_test
  username: root
  password: 2009060944
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: defaultdb
  username: avnadmin
  password: AVNS_-uw25sgnoMPvDKax1us
  url: postgres://avnadmin:AVNS_-uw25sgnoMPvDKax1us@rewardboy-manishdahiya0944-3d19.c.aivencloud.com:28716/defaultdb?sslmode=require
  port: 28716
